Migrate to JUnit 5
apache/commons-beanutils pull request #283
Opened 2024-08-31 23:03 UTC by stevebosman

I've updated a lot of the remaining tests to JUnit 5

I think this will leave the tests extending the following to do:

* `AbstractDateConverterTest`
* `AbstractNumberConverterTest`
* `BaseLocaleConverterTest`

2024-08-31 23:50 UTC, garydgregory requested changes
Hello @stevebosman 

Thank you for your PR. 

It will take a lot longer to review a PR when it contains unnecessary changes like editing public/protected/private. Also please keep the style to use static imports only for assertion methods. This will all reduce the noise in the change set a lot.

IMO a PR for this task is not about creating the prettiest code but creating a change set that easier for a maintainer to review, and there are 105 files changed here 😉

2024-09-01 12:28 UTC, stevebosman commented
I've added the changes for static imports. I've also reverted the visibility changes. I think I've caught all of them, but will have another look later. My fault for trusting my IDE's refactoring too much :)

2024-09-01 12:48 UTC, garydgregory commented
@stevebosman 

Thank you for your update. Yeah, all IDEs I've tried mess up the conversion or leaves you with code that does not even compile (I'm looking at you IntelliJ...)

Another item that would be nice to have (but don't feel obligated):
```
assertTrue(e.toString().contains("Unknown property"), "Wrong exception was thrown: " + e);
```
->
```
assertTrue(e.toString().contains("Unknown property"), () -> "Wrong exception was thrown: " + e);
```
which will avoid creating garbage Strings in the majority of build runs.

2024-09-01 17:56 UTC, stevebosman commented
I have fixed that one and the few others in `BeanComparatorTestCase`. There are similar in some other test files, but my instinct is they should be addressed in another much smaller PR.

2024-09-01 22:27 UTC, garydgregory commented on src/test/java/org/apache/commons/beanutils2/WrapDynaBeanTestCase.java
> +            // Assert.assertTrue("Can not see unknown key",
Odd comment change ;-)

2024-09-01 22:28 UTC, garydgregory commented on src/test/java/org/apache/commons/beanutils2/bugs/Jira157TestCase.java
>      }
So this method can be removed?

2024-09-01 22:28 UTC, garydgregory commented on src/test/java/org/apache/commons/beanutils2/bugs/Jira273TestCase.java
> -        super.setUp();
Remove method?

2024-09-01 22:29 UTC, garydgregory commented on src/test/java/org/apache/commons/beanutils2/bugs/Jira273TestCase.java
> -        super.tearDown();
Remove method?

2024-09-01 22:29 UTC, garydgregory commented on src/test/java/org/apache/commons/beanutils2/bugs/Jira298TestCase.java
> -        super.setUp();
Remove method?

2024-09-01 22:29 UTC, garydgregory commented on src/test/java/org/apache/commons/beanutils2/bugs/Jira298TestCase.java
> -        super.tearDown();
Remove method?

2024-09-01 22:34 UTC, garydgregory approved these changes
LGTM, I made a few notes, but I'll merge as is.

2024-09-01 22:35 UTC, merged